export const webpage = `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Comms Hub</title><style>
:root{color-scheme:dark}*{box-sizing:border-box}body{margin:0;height:100dvh;display:flex;flex-direction:column;background:#0a0a0a;color:#e8e8e8;font:14px/1.35 ui-monospace,"SF Mono",Menlo,Consolas,monospace}
header{display:flex;justify-content:space-between;padding:10px 12px;border-bottom:1px solid #222}#status{font-size:12px;color:#aaa;display:flex;gap:7px;align-items:center}.dot{width:9px;height:9px;border-radius:999px;background:#cc3344}.green{background:#44cc66}.amber{background:#f5a623}
#log{flex:1;overflow:auto;padding:10px}.m{margin:0 0 10px;white-space:pre-wrap}.h{font-weight:700;color:#f5a623}.t{color:#8a8a8a;margin-right:8px}
form{position:sticky;bottom:0;border-top:1px solid #222;background:#101010;padding:8px;display:grid;gap:8px}.row{display:grid;grid-template-columns:1fr 1fr auto;gap:8px}
input,select,textarea,button{background:#151515;color:#e8e8e8;border:1px solid #333;border-radius:6px;padding:8px;font:inherit}textarea{min-height:70px;resize:vertical}button{min-width:82px}
@media (max-width:680px){.row{grid-template-columns:1fr}}
</style></head><body><header><b>Comms Hub</b><div id="status"><span id="dot" class="dot"></span><span id="stat">connecting…</span></div></header><div id="log"></div><form id="f"><div class="row"><input id="from" value="David" placeholder="From"><select id="to"><option>All</option></select><button>Send</button></div><textarea id="content" placeholder="Message"></textarea></form><script>
const logEl=document.getElementById('log'),fromEl=document.getElementById('from'),toEl=document.getElementById('to'),contentEl=document.getElementById('content'),dot=document.getElementById('dot'),stat=document.getElementById('stat');
let lastSeen=0,lastOk=0,lastErr=0,first=true,audioCtx=null;
const nearBottom=()=>logEl.scrollTop+logEl.clientHeight>=logEl.scrollHeight-24;
const hm=t=>new Date(t).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'});
function initAudio(){if(audioCtx)return;try{audioCtx=new (window.AudioContext||window.webkitAudioContext)()}catch{}}
document.body.addEventListener('click',initAudio,{once:true});
function ding(){if(!audioCtx)return;try{const now=audioCtx.currentTime,o1=audioCtx.createOscillator(),o2=audioCtx.createOscillator(),g=audioCtx.createGain();o1.frequency.value=440;o2.frequency.value=660;o1.type=o2.type='sine';g.gain.setValueAtTime(0.3,now);g.gain.linearRampToValueAtTime(0.0001,now+0.15);o1.connect(g);o2.connect(g);g.connect(audioCtx.destination);o1.start(now);o2.start(now);o1.stop(now+0.15);o2.stop(now+0.15)}catch{}}
function add(m){const d=document.createElement('div');d.className='m';const t=document.createElement('span');t.className='t';t.textContent='['+hm(m.created_at)+']';const h=document.createElement('span');h.className='h';h.textContent=m.from_name+(m.to_name?' → '+m.to_name:'');const c=document.createElement('div');c.textContent=m.content;d.append(t,h,c);logEl.appendChild(d)}
async function refreshParticipants(){const r=await fetch('/participants');if(!r.ok)return;const names=await r.json();const keep=toEl.value;toEl.innerHTML='<option>All</option>';for(const n of names){const o=document.createElement('option');o.value=n;o.textContent=n;toEl.appendChild(o)}toEl.value=[...toEl.options].some(o=>o.value===keep)?keep:'All'}
function setStatus(){const age=Date.now()-lastOk;dot.className='dot';if(lastErr||!lastOk||age>15000){stat.textContent='error '+new Date(lastErr||Date.now()).toLocaleTimeString();return}if(age>6000){dot.classList.add('amber');stat.textContent='stale '+new Date(lastOk).toLocaleTimeString();return}dot.classList.add('green');stat.textContent='ok '+new Date(lastOk).toLocaleTimeString()}
async function poll(){try{const r=await fetch('/read?since='+lastSeen);if(!r.ok)throw new Error();const ms=await r.json();const stick=nearBottom();for(const m of ms){add(m);if(m.created_at>lastSeen)lastSeen=m.created_at}if(!first&&ms.length)ding();if(first||stick)logEl.scrollTop=logEl.scrollHeight;first=false;lastOk=Date.now();lastErr=0}catch{lastErr=Date.now()}setStatus()}
document.getElementById('f').onsubmit=async e=>{e.preventDefault();const from=fromEl.value.trim(),content=contentEl.value.trim(),to=toEl.value==='All'?null:toEl.value;if(!from||!content)return;const r=await fetch('/post',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({from,to,content})});if(r.ok)contentEl.value=''};
contentEl.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key==='Enter')document.getElementById('f').requestSubmit()});
setInterval(poll,3000);setInterval(refreshParticipants,30000);setInterval(setStatus,1000);poll();refreshParticipants();
</script></body></html>`;
